import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import MyAppBar from "../components/MyAppBar";
import MyFooter from "../components/MyFooter";
import { Box, margin, padding } from "@mui/system";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>
        <MyAppBar></MyAppBar>
        </header>
        <Box sx={{
          marginTop: 10,
        }}>
        {children}
        </Box>
        <footer sx={{
          margin: 0,
          padding: 0,
        }}>
          <MyFooter></MyFooter>
        </footer>
      </body>
    </html>
  );
}
